networks:
  traefik:
    external: true
  ranger:
    external: true
  
volumes:
  ranger-db:
  ranger-solr:

services:
  ranger-admin:
    labels:
      - traefik.enable=true
      - traefik.http.routers.ranger-admin.rule=Host(`ranger.flavindias.com.br`) || Host(`www.ranger.flavindias.com.br`)
      - traefik.http.services.ranger-admin.loadbalancer.server.port=6080

      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.ranger-admin.middlewares=mywwwredirect
      
    build:
      context: ./ranger-admin
      dockerfile: Dockerfile
    container_name: ranger-admin
    restart: always
    networks:
      - traefik
      - ranger
    expose:
      - 6080
    depends_on:
      - ranger-db
      - ranger-solr

  ranger-db:
    image: postgres
    hostname: ranger-db
    container_name: ranger-db
    restart: always
    networks:
      - ranger
    volumes:
      - ranger-db:/var/lib/postgresql
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres

  ranger-solr:
    image: solr:8.11.2
    container_name: ranger-solr
    restart: always
    networks:
      - ranger
    expose:
      - 8983
    volumes:
      - ranger-solr:/opt/solr/server/solr/configsets/ranger_audits/conf
    entrypoint:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits
